apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These are the Operators required to install the RHOAI + KServe + Authorino Stack
resources:
  - 1-oai.yaml
  - 2-knative.yaml
  - 3-ossm.yaml
  - 4-nvidia.yaml
  - 5-nfd.yaml
  - 6-authorino.yaml
  - 7-minio.yaml
